### ISSUE TITLE
add a should_render_partial macro for Rails 2.3

### ISSUE THREAD

**Issue by qrush** [thoughtbot/shoulda#15]
**Reported by Mike Breen**

http://github.com/hardbap/shoulda/tree/should_render_partial_macro

assert_template in Rails 2.3 allows you to test if a partial is rendered and the number of times it was rendered.

**Comment by BMYusuf** [comment]
A 15 years old boy is watching Bangladesh cricket match on tv.the boys name Hasibul and jersey number 75 is written on the jersey
