### ISSUE TITLE
shoulda-matchers with just ActiveModel

### ISSUE THREAD

**Issue by kalasjocke** [thoughtbot/shoulda#184]
Hi,

I am trying to use shoulda-matchers outside of Rails, just with ActiveModel. Is this possible? I have the following code, and it fails when i want to use one of the custom shoulda matchers.

Gemfile:

```
gem "activemodel"

group :test do
  gem "rspec-rails"
  gem "shoulda-matchers"
end
```

lib/fruit.rb:

```
require 'active_model'

class Fruit
  include ActiveModel::Validations

  attr_accessor :color
end
```

spec/fruit_spec.rb:

```
require 'fruit'

describe Fruit do
  it { should validate_presence_of(:color) }
end
```

and finally if fails with:

```
Fruit
   (FAILED - 1)

Failures:

  1) Fruit 
     Failure/Error: it { should validate_presence_of(:color) }
     NoMethodError:
       undefined method `validate_presence_of' for #<RSpec::Core::ExampleGroup::Nested_1:0x00000101763228>
     # ./spec/fruit_spec.rb:4:in `block (2 levels) in <top (required)>'

Finished in 0.00054 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/fruit_spec.rb:4 # Fruit 
```

I am missing something here? Big thanks by the way for a great gem!

**Comment by xtrasimplicity** [comment]
I had these issues and none of the solutions above resolved it. It turns out, I'd forgotten to specify the _type_ of object I was testing, in my specs. i.e.

```ruby
RSpec.describe User do # This will raise an error.
```

instead of 
```ruby
RSpec.describe User, type: :model do # This works OK.
```

**Comment by mcmire** [comment]
@xtrasimplicity The docs assume that you have `infer_spec_type_from_location!` turned on, as what rspec-rails will place in rails_helper.rb automatically: https://github.com/rspec/rspec-rails/blob/master/lib/generators/rspec/install/templates/spec/rails_helper.rb#L72. If you have this line commented out or do not have this line present at all, then you will need to tag example groups manually.

**Comment by xtrasimplicity** [comment]
Thanks, @mcmire. I'm not using Rails (and am therefore using the `rspec` gem rather than `rspec-rails`), so that would explain it.
