### ISSUE TITLE
time error in minitest

### ISSUE THREAD

**Issue by gameFu** [thoughtbot/shoulda#260]
in a test case , I use `travel_to 1.days.since` modify current_time
![image](https://cloud.githubusercontent.com/assets/11696134/14075775/a316978c-f50e-11e5-834d-1cef2f571be9.png)
in other test case,  the current_time no back to the right time
![image](https://cloud.githubusercontent.com/assets/11696134/14075944/0eade986-f510-11e5-915d-dfa9dabdee01.png)

**Comment by tejasbubane** [comment]
Can you please paste some test code here? It is difficult to get from the screenshots but from what I see, `travel_to` stubs the current date and it is still in scope when you are checking it again.

**Comment by gameFu** [comment]
But,the two test case in in different files。
in collection_controller_test.rb 
![image](https://cloud.githubusercontent.com/assets/11696134/14095729/bc290f3e-f595-11e5-9917-2b0d55df6b49.png)
in playcounts_test.rb
![image](https://cloud.githubusercontent.com/assets/11696134/14095786/596a4682-f596-11e5-8258-3d56a719e677.png)

**Comment by mcmire** [comment]
You should be using the block form of `travel_to` to ensure that time is unfrozen between tests:

``` ruby
travel_to Date.new(2017, 1, 1) do
  # ...
end
```

Closing since there hasn't been activity on this issue in a while.
