### ISSUE TITLE
Rubygems.org not updated with latest version

### ISSUE THREAD

**Issue by wakproductions** [thoughtbot/shoulda#262]
Trying to use v3.5 but the highest version available thru Rubygems.org is 3.1. Need to link directly to the Github to use the latest becuase `gem 'shoulda-matchers', '~> 3.5'` won't work.

**Comment by mcmire** [comment]
@wakproductions Are you still having this issue? RubyGems is saying that 3.5.0 has been available for a while now: https://rubygems.org/gems/shoulda

**Comment by wakproductions** [comment]
I think I worked around this issue... it was confusion between `shoulda` and `shoulda-matchers`. https://rubygems.org/gems/shoulda-matchers
