### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by CodingAnarchy** [thoughtbot/shoulda#265]
Is the repository still maintained, or should we use the `shoulda-matchers` and `shoulda-context` directly?  Those two seem to be updated periodically, but this is not.

**Comment by Schwad** [comment]
@CodingAnarchy good question, I posted directly to thoughtbot on Twitter maybe a month ago about this and got no response as well. Guess I'll shoot in a PR myself as we ran into a pain point with this on a Rails 5.2.0 upgrade.

**Comment by iamwhil** [comment]
We had to roll back to 3.5 as 3.6 stopped playing nicely with shoulda-matchers.
We started getting "undefined method `validate_presence_of' for #<RSpec::" errors all over the place.  That and every other shoulda-matcher method.  validate-inclusion-of, belong_to, etc.

**Comment by nickcharlton** [comment]
To answer the original question: Yes in the sense that someone is reading and triaging issues, No in the sense that I often don't make much progress on doing those given time constraints.

@iamwhil I'd suggest opening a new issue about that. It's _possible_ that you're seeing known issues w/`shoulda-matchers`, as I know there's a few there.

I'm going to close this otherwise.

**Comment by jasonperrone** [comment]
I think this is a valid question. There are new features in should_matchers that I am not getting by using this gem.

**Comment by jasonperrone** [comment]
@mcmire thanks for that. I am a little confused though. So, I see that you pushed the changes to the main master branch, which is good. My Gemfile does not have shoulda locked to any particular version, so shouldn't "bundle update shoulda" have picked it up? It didn't, it's still seeing the latest version as 3.6.0 which is also what README.md says. I am sure I am doing something wrong, so please forgive me :)

**Comment by jasonperrone** [comment]
NVM, this worked
```
gem 'shoulda', '~> 4.x'
```

I'll let you know how my tests go. Thanks again.

**Comment by jasonperrone** [comment]
My solution above is not working anymore. What happened?

**Comment by jasonperrone** [comment]
Had to do this:  
```
gem 'shoulda', git: 'https://github.com/thoughtbot/shoulda.git', branch: :master
```

Honestly wish I didn't have to do that.

**Comment by mcmire** [comment]
I'm not sure how it worked before, but Bundler doesn't usually pick up pre-releases by default.
