### ISSUE TITLE
Migrations incompatibilities in Rails 5.1+

### ISSUE THREAD

**Issue by voxik** [thoughtbot/shoulda#267]
Running test suite against Rails 5.2, I observer following error:

~~~
... snip ...

       StandardError: An error has occurred, this and all later migrations canceled:
        
        Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
        
          class CreateUsers < ActiveRecord::Migration[4.2]
        /usr/share/gems/gems/activerecord-5.2.1/lib/active_record/migration.rb:528:in `inherited'
        /builddir/build/BUILD/shoulda-3.6.0/usr/share/gems/gems/shoulda-3.6.0/tmp/acceptance/test-project/db/migrate/1_create_users.rb:1:in `<top (required)>'

... snip ...
~~~

It seems that similar medicine to https://github.com/thoughtbot/shoulda-matchers/commit/b310986f9a3b7547c98e54db97600f8128e28ff5 is needed here.

**Comment by voxik** [comment]
And this https://github.com/thoughtbot/shoulda-matchers/commit/158839b3a60f0c2a1f243f6e65ec620be55982ee is required as well.

**Comment by mcmire** [comment]
Thanks for reporting this! I'm sure we will find other little things like this when we upgrade the gem to support Rails 5 (and the upcoming shoulda-matchers 4).

**Comment by mcmire** [comment]
I just pushed up a bunch of updates to make the tests run against Rails 5.2, so this should be fixed now.
