### ISSUE TITLE
2.11.3 broken by rake 12.3.3

### ISSUE THREAD

**Issue by izcet** [thoughtbot/shoulda#268]
Original ticket [here](https://github.com/ruby/rake/issues/323), cross-posting for context and awareness.

**Comment by mcmire** [comment]
Hey, sorry for not responding to this sooner (switched to the new notifications recently and this must have not come up). I don't know quite what's happening in your report or why you would be getting that, but the newest version of shoulda is 3.6.0 and we don't support 2.x anymore, so I'm not sure what we could do about this.

**Comment by mcmire** [comment]
Closing due to staleness.
